model:
  name: meta-llama/Meta-Llama-3.1-8B
  max_new_tokens: 64
rauq:
  alpha: 0.2
datasets:
  - name: truthfulqa
    config: configs/datasets/truthfulqa.yaml
  - name: mmlu
    config: configs/datasets/mmlu.yaml
gating:
  spike:
    tau_abs: 6.0
    tau_rel: 2.5
    window: 4
    refractory: 3
output_root: data/experiments
